config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :cars
  resources :bookings
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  # Validations
  validates :car_id, :starts_at, :ends_at, presence: true

  # Associations
  belongs_to :car
  belongs_to :user

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :brand, :model, :year_of_production, :address, :price_per_day, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy, foreign_key: 'user_id'
  has_many :bookings, dependent: :destroy

end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#   before_action :authenticate_user!
#   include Pundit::Authorization

#   rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

#   after_action :verify_authorized, except: :index, unless: :skip_pundit?
#   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

#   def policy_scope(scope, policy_scope_class: nil, context: {})
#     policy_scope_class ||= Pundit::PolicyFinder.new(scope).scope!
#     policy_scope_class.new(pundit_user, scope, context).resolve
#   end

#   private

#   def skip_pundit?
#     devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
#   end

#   def default_url_options
#     { host: ENV["DOMAIN"] || "localhost:3000" }
#   end

# end

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :process_date_range, only: [:create, :update]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = current_user.bookings.build
    authorize @booking
  end

  def edit
    @booking = current_user.bookings.find(params[:id])
    authorize @booking
  end

  def create
    # starts_at, ends_at = params[:booking][:date_range].split(" to ")
    # process_date_range
    @booking = current_user.bookings.build(booking_params)
    authorize @booking

    if @booking.save
      redirect_to booking_path(@booking), notice: 'Booking request has been sent.'
    else
      render :new
    end
  end

  def update
    @booking = current_user.bookings.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end
  

  def destroy
    @booking = current_user.bookings.find(params[:id])
    authorize @booking
    if @booking.destroy
      flash[:notice] = 'Your booking was cancelled successfully'
    else
      puts "Failed to destroy booking: #{@booking.errors.full_messages}"
      flash[:errors] = @booking.errors.full_messages
    end
    redirect_to booking_path(@booking)
  end

  private

  def process_date_range
    if params[:booking][:date_range].present?
      starts_at, ends_at = params[:booking][:date_range].split(" to ")
      params[:booking][:starts_at] = starts_at
      params[:booking][:ends_at] = ends_at
    end
  end
  
  def booking_params
    params.require(:booking).permit(:user_id, :car_id, :starts_at, :ends_at, :accepted)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @cars = policy_scope(Car)
  end

  def show
    @car = Car.find(params[:id])
    authorize @car
  end

  def new
    @car = current_user.cars.build
    authorize @car
  end

  def create
    @car = current_user.cars.build(car_params)
    authorize @car
    if @car.save
      redirect_to car_path(@car), notice: 'Car was successfully created.'
    else
      render :new
    end
  end

  def edit
    @car = current_user.cars.find(params[:id])
    authorize @car
  end

  def update
    @car = current_user.cars.find(params[:id])
    authorize @car
    if @car.update(car_params)
      redirect_to car_path(@car), notice: 'Your new car was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @car = current_user.cars.find(params[:id])
    authorize @car

    if @car.delete
      flash[:notice] = 'Your car was deleted successfully'
      redirect_to cars_path
    else
      flash[:errors] = @car.errors.full_messages
      redirect_to destroy_car_path
    end
  end

  private
  def car_params
    params.require(:car).permit(:brand, :model, :year_of_production, :address, :price_per_day)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def about_us
  end

  def contact_us
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%# <div data-controller="hello">
  <input data-hello-target="name" type="text">
  <button data-action="click->hello#greet">Greet</button>
</div> %>

<%= form_with model: @booking, local: true, data: { controller: "flatpickr" } do |form| %>

  <%= form.label :user_id, 'User' %>
    <p><%= current_user.email %></p>



  <div>
    <%= form.label :date_range, 'Date Range' %>
    <%= form.text_field :date_range, class: 'fp_date_time', data: { controller: 'flatpickr' } %>
  </div>

  <%= form.hidden_field :starts_at, value: "", data: { flatpickr_target: 'startsAt' } %>
  <%= form.hidden_field :ends_at, value: "", data: { flatpickr_target: 'endsAt' } %>

<%# 
  <div>
    <%= form.label :starts_at, 'Starts at' 
    <%= form.text_field :starts_at, class: 'fp_date_time' 
  </div>

  <div>
    <%= form.label :ends_at, 'Ends at' 
    <%= form.text_field :ends_at, class: 'fp_date_time'
  </div> %>

  <div>
    <%= form.label :car_id, 'Car' %>
    <%= form.collection_select :car_id, Car.all.where.not(id: current_user.cars.pluck(:id)), :id, :model, prompt: 'Select a Car' %>
  </div>
  
  <div>
    <%= form.submit 'Request Booking' %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1 data-controller="hello">All Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Car</th>
      <th>Starts At</th>
      <th>Ends At</th>
      <th>Accepted</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.car.user.email.split('@').first.capitalize %></td>
        <td><%= booking.car.brand %> <%= booking.car.model %></td>
        <td><%= booking.starts_at.strftime("%A, %d-%m-%Y") %></td>
        <td><%= booking.ends_at.strftime("%A, %d-%m-%Y") %></td>
        <td><%= booking.accepted ? 'Yes' : 'No' %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Return', root_path %>
<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<%# <div data-controller="flatpickr"> %>
<%= render 'form' %>
</div>
<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p><strong>User:</strong> <%= @booking.user.email %></p>
<p><strong>Car:</strong> <%= @booking.car.brand %> <%= @booking.car.model %></p>
<p><strong>Starts At:</strong> <%= @booking.starts_at %></p>
<p><strong>Ends At:</strong> <%= @booking.ends_at %></p>
<p><strong>Accepted:</strong> <%= @booking.accepted ? 'Yes' : 'No' %></p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/cars/_form_edit.html.erb
<div class="form-inputs">
  <% if @car.errors.any? %>
    <% @car.errors.full_messages.each do |error| %>
      <p style="color: orange"><%= error %></p>
    <% end %>
  <% end %>
  <%= simple_form_for @shipment, html: { id: "edit_car" }, data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :brand, disabled: true %>
    <%= f.input :model, disabled: true %>
    <%= f.input :year_of_production, disabled: true %>
    <%= f.input :address, disabled: true %>
    <%= f.input :price_per_day, disabled: true %>

    <%= f.button :submit, 'Update car', class: 'btn btn-light custom-bg-blue' %>
  <% end %>
  

app/views/cars/_form_new.html.erb
<div class="form-inputs">
  <% if @car.errors.any? %>
    <% @car.errors.full_messages.each do |error| %>
      <p style="color: orange"><%= error %></p>
    <% end %>
  <% end %>
  <%= simple_form_for @shipment, html: { id: "edit_car" }, data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :brand, disabled: true %>
    <%= f.input :model, disabled: true %>
    <%= f.input :year_of_production, disabled: true %>
    <%= f.input :address, disabled: true %>
    <%= f.input :price_per_day, disabled: true %>

    <%= f.button :submit, 'Update car', class: 'btn btn-light custom-bg-blue' %>
  <% end %>
  

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= simple_form_for @car do |f| %>
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :year_of_production %>
  <%= f.input :address %>
  <%= f.input :price_per_day %>

  <div class="actions">
    <%= f.button :submit, 'Update Car' %>
  </div>
<% end %>

<%= link_to 'Cancel', car_path(@car) %>

app/views/cars/index.html.erb
<h1>All Cars</h1>

<div id="map" data-controller="leafletmapping" data-leafletmapping-target="map" style="height: 400px;"></div>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Year of Production</th>
      <th>Address</th>
      <th>Price Per Day</th>
      <th>Car's Owner</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.year_of_production %></td>
        <td><%= car.address %></td>
        <td><%= car.price_per_day %></td>
        <td><%= car.user.email.split('@').first.capitalize %></td>
        <td>
          <%= link_to 'Show', car %>
          <% if policy(car).edit? %>
            <%= link_to 'Edit', edit_car_path(car) %>
          <% end %>
          <button class="show-location" data-car-address="<%= car.address %>" data-leafletmapping-target="button">Show Location</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Return', root_path %>
<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= simple_form_for @car do |f| %>
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :year_of_production %>
  <%= f.input :address %>
  <%= f.input :price_per_day %>

  <div class="actions">
    <%= f.button :submit, 'Create Car' %>
  </div>
<% end %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<h1><%= @car.brand %> <%= @car.model %></h1>

<p><strong>Year of Production:</strong> <%= @car.year_of_production %></p>
<p><strong>Address:</strong> <%= @car.address %></p>
<p><strong>Price Per Day:</strong> <%= @car.price_per_day %></p>
<p><strong>Owner's Email:</strong> <%= @car.user.email %></p>
<% if policy(@car).edit? %>
  <%= link_to 'Edit', edit_car_path(@car) %>
  <%= link_to 'Destroy', car_path(@car), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentCarsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://ga.jspm.io/npm:flatpickr@4.6.9/dist/flatpickr.min.css">
    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <!-- Leaflet Control Geocoder CSS -->
    <%# <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" /> %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <!-- Leaflet JavaScript -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
        <!-- Leaflet Control Geocoder JavaScript -->
    <%# <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script> %>

  </body>
</html>

app/views/pages/home.html.erb
<h1> Hello, <%= current_user.email.split('@').first.capitalize %></h1>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "Manage my bookings", bookings_path %>
<%= link_to "Cars for rent", cars_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
  
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>